# Generated by Django 5.1.2 on 2024-10-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
