# Generated by Django 5.1.2 on 2024-10-25 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_devices_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('when_local', models.DateTimeField()),
                ('pm1', models.FloatField(blank=True, null=True)),
                ('pm25', models.FloatField(blank=True, null=True)),
                ('pm4', models.FloatField(blank=True, null=True)),
                ('pm10', models.FloatField(blank=True, null=True)),
                ('pm25aqi', models.FloatField(blank=True, null=True)),
                ('pm10aqi', models.FloatField(blank=True, null=True)),
                ('pm05nc', models.FloatField(blank=True, null=True)),
                ('pm1nc', models.FloatField(blank=True, null=True)),
                ('pm25nc', models.FloatField(blank=True, null=True)),
                ('pm4nc', models.FloatField(blank=True, null=True)),
                ('pm10nc', models.FloatField(blank=True, null=True)),
                ('tps', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('co2', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('etoh', models.FloatField(blank=True, null=True)),
                ('tvoc', models.FloatField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='devices.devices')),
            ],
        ),
    ]
